### ISSUE TITLE
Update did not upgrade some plgx

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Rookiestyle/EarlyUpdateCheck#33]
## Overview
![Overview](https://user-images.githubusercontent.com/46166740/144062684-e7e68f10-e8f6-4dc9-812e-cec3a251ac57.png)
## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Press update button
2. accept UAC prompt
3. find `"C:\Program Files (x86)\KeePass Password Safe 2\Plugins\PasswordChangeAssistant.plgx"` not updated

## Expected Behavior
plgx file replaced with new version. Find new Version after restart KeePass.

## Actual Behavior
Nothing happens? But prompts to update again after next update check.

While it worked great for updating your other Plugin [ColoredPassword](https://github.com/Rookiestyle/ColoredPassword), the updater did not update this plugin:

- PasswordChangeAssistant
- PEDCalc
- KeePass Sync For Google Drive

## Context
[NOTE]: # (Provide any additional information you may have)
OS: win11
KeePass Version: 2.49
Plugin Version: 3.5

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
That's weird, I was not able to reproduce this.

Would you mind attaching a debug file?
It should be sufficient to activate debug mode before doing the update check and auto update.
https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/Create-a-debugfile

**Comment by Rookiestyle** [comment]
According to your screenshot, you have pretty old versions of PasswordChangeAssistant and PEDCalc installed.
Those versions are from SourceForge which I used prior to Github.
You need to manually update this time and auto update will work for all future releases.

For KeePass Sync For Google Drive I still need the debug file.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
according to the debug log, the download failed:

404 <Param>Source: https://github.com/walterpg/google-drive-sync/releases/latest/download/KPSyncForDrive-4.0.6-beta.plgx</Param>

correct link would be:
https://github.com/walterpg/google-drive-sync/releases/download/v4.0.6-beta/KPSyncForDrive-4.0.6-beta.plgx

btw.  4.0.7-beta is Latest

**Comment by Rookiestyle** [comment]
KeePass' update check depends on plugins to tell KeePass where infomration about the newest version can be found.

You are running KeePass Sync For Google Drive with a version lower than 4.0.6
These versions of the plugin tell KeePass to check this file: https://github.com/walterpg/google-drive-sync/blob/master/kpsync_version_4.txt
As this file returns 4.0.6 as newest version two things happen
1. KeePass itself will report 4.0.6 as newest version instead of 4.0.7
2. EarlyUpdateCheck will try to download 4.0.6 instead of 4.0.7
Neither KeePass nor EarlyUPdateCheck has a chance to know about 4.0.7

Download would work if the plugin's filename would not contain the version.

Starting with 4.0.6 KeePass Sync For Google Drive got named to KPSync For Google Drive and KeePass is told to use this file: https://github.com/walterpg/google-drive-sync/blob/master/kpsync_final.txt
Here, 4.0.7 is reported as newest version but this will be known to KeePass (and in consequence to my plugin) only after having updated to 4.0.6 
Details: https://www.kpsync.org/install/upgrade0

**Comment by Rookiestyle** [comment]
I found a way to bypass this - at least to a certain extent.

Next time you start KeePass, EarlyUpdateCheck should inform you about a new version of ExternalPluginUpdates.xml
Once downloaded, it will download 4.0.6  - that's the version it is aware of.

There is no way for my plugin to download the newest version in only one step.
You also need to manually replace your 4.0.5 files or whatever version you currently use.
Version before 4.0.6 are shipped as dll instead of plgx and you can't delete dll files while they are loaded.

After a restart of KeePass you can download 4.0.7. On my device this was then displayed as newest version.
Please be informed about 4.0.7 release notes: https://github.com/walterpg/google-drive-sync/releases/tag/v4.0.7-beta
`Installation NOTE: For .PLGX upgrades from v4.0.6-beta to this release, you are required to first purge the KeePass plugin cache for the upgrade to succeed. Sorry for any inconvenience - the next release will not have this requirement.`

Let me know whether it works for you


Anyhow: As this plugin will not be renamed again according to the author, update to future version will work as planned

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Next time you start KeePass, EarlyUpdateCheck should inform you about a new version of ExternalPluginUpdates.xml

Yes.

> Once downloaded, it will download 4.0.6 - that's the version it is aware of.

Yes, successfully.


> There is no way for my plugin to download the newest version in only one step. You also need to manually replace your 4.0.5 files or whatever version you currently use. Version before 4.0.6 are shipped as dll instead of plgx and you can't delete dll files while they are loaded.
> 

I did not replace it manually. Sorry for missing the old version information in this issue. 

There is a workaround for the loaded DLL file updating. You can NOT delete a used  DLL plugin file or overwrite it. But you can actually rename it to let's say RuleBuilder.dll.bak and download new RuleBuilder.dll at the same location. Next KeePass startup, the updated version will be loaded. ;)

This could be useful for upgrading any DLL based Plugins, I guess.


> After a restart of KeePass you can download 4.0.7. On my device this was then displayed as newest version. Please be informed about 4.0.7 release notes: https://github.com/walterpg/google-drive-sync/releases/tag/v4.0.7-beta `Installation NOTE: For .PLGX upgrades from v4.0.6-beta to this release, you are required to first purge the KeePass plugin cache for the upgrade to succeed. Sorry for any inconvenience - the next release will not have this requirement.`
> 


Yes, the KPSyncForDrive-4.0.7-beta.plgx was downloaded after upgrade to 4.0.6-beta.plgx through EarlyUpdateCheck. While KPSyncForDrive-4.0.7-beta.plgx exists in Plugins directory, KeePass showed 4.0.6 because of caching. Purge caches helped in this case, thanks.
